on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./azuredeploy.json
        parameters:
        - name: hostingPlanName
          values:
          - socketbot_App_service_plan
        - name: webSiteName
          values:
          - vendredi_13_mai_2022
        - name: skuName
          values:
          - F1
        - name: skuCapacity 1
          values:
          - location westeurope

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
