# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - socketbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Make Unit Test
        run: pytest --luisappid ${{ secrets.LUIS_APP_ID }} --luisapikey ${{ secrets.LUIS_API_KEY }} --luisapihostname ${{ secrets.LUIS_API_HOST_NAME }} tests/
      - name: Environment variables
        run: export APP_ID=${{ secrets.APP_ID }} &&\
              export APP_PASSWORD=${{ secrets.APP_PASSWORD }} &&\
              export LUIS_APP_ID=${{ secrets.LUIS_APP_ID }} &&\
              export LUIS_API_KEY=${{ secrets.LUIS_API_KEY }} &&\
              export LUIS_API_HOST_NAME=${{ secrets.LUIS_API_HOST_NAME }} &&\
              export LUIS_AUTH_KEY=${{ secrets.LUIS_AUTH_KEY }} &&\ 
              export LUIS_AUTH_ENDPOINT=${{ secrets.LUIS_AUTH_ENDPOINT }} &&\
              export APPINSIGHTS_INSTRUMENTATION_KEY=${{ secrets.APPINSIGHTS_INSTRUMENTATION }}

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'socketbot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_36729078B17D4AAE8632D6BDF15E0EC4 }}
